{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": "",
    "description": ""
  },
  "paths": {
    "/stores/{storeId}": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "examples": {
              "application/json": {
                "storeId": 12345,
                "storeName": "WooCommerce Store",
                "marketplaceId": 36,
                "marketplaceName": "WooCommerce",
                "accountName": null,
                "email": null,
                "integrationUrl": "http://shipstation-test.wpengine.com",
                "active": true,
                "companyName": "",
                "phone": "",
                "publicEmail": "",
                "website": "",
                "refreshDate": "2014-12-16T17:47:05.457",
                "lastRefreshAttempt": "2014-12-16T09:47:05.457",
                "createDate": "2014-11-06T15:21:13.223",
                "modifyDate": "2014-11-10T08:02:19.117",
                "autoRefresh": true,
                "statusMappings": [
                  {
                    "orderStatus": "awaiting_payment",
                    "statusKey": "Pending"
                  },
                  {
                    "orderStatus": "awaiting_shipment",
                    "statusKey": "Processing"
                  },
                  {
                    "orderStatus": "shipped",
                    "statusKey": "Completed"
                  },
                  {
                    "orderStatus": "cancelled",
                    "statusKey": "Cancelled"
                  },
                  {
                    "orderStatus": "on_hold",
                    "statusKey": "On-hold"
                  }
                ]
              }
            },
            "schema": {
              "$ref": "#/definitions/Get~1Update StoreModel"
            }
          }
        },
        "summary": "Get Store",
        "operationId": "Get Store",
        "description": "",
        "tags": [
          "Stores"
        ],
        "parameters": [
          {
            "name": "storeId",
            "in": "path",
            "description": "A unique ID generated by ShipStation and assigned to each store.",
            "required": true,
            "x-example": "12345",
            "type": "number"
          }
        ],
        "produces": [
          "application/json"
        ]
      },
      "put": {
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "examples": {
              "application/json": {
                "storeId": 12345,
                "storeName": "WooCommerce Store",
                "marketplaceId": 36,
                "marketplaceName": "WooCommerce",
                "accountName": null,
                "email": null,
                "integrationUrl": "http://shipstation-test.wpengine.com",
                "active": true,
                "companyName": "",
                "phone": "",
                "publicEmail": "",
                "website": "",
                "refreshDate": "2014-12-16T17:47:05.457",
                "lastRefreshAttempt": "2014-12-16T09:47:05.457",
                "createDate": "2014-11-06T15:21:13.223",
                "modifyDate": "2014-11-10T08:02:19.117",
                "autoRefresh": true,
                "statusMappings": [
                  {
                    "orderStatus": "awaiting_payment",
                    "statusKey": "Pending"
                  },
                  {
                    "orderStatus": "awaiting_shipment",
                    "statusKey": "Processing"
                  },
                  {
                    "orderStatus": "shipped",
                    "statusKey": "Completed"
                  },
                  {
                    "orderStatus": "cancelled",
                    "statusKey": "Cancelled"
                  },
                  {
                    "orderStatus": "on_hold",
                    "statusKey": "On-hold"
                  }
                ]
              }
            },
            "schema": {
              "$ref": "#/definitions/Get~1Update StoreModel"
            }
          }
        },
        "summary": "Update Store",
        "operationId": "Update Store",
        "description": "Updates an existing store. This call does not currently support partial updates. The entire resource must be provided in the body of the request.",
        "tags": [
          "Stores"
        ],
        "parameters": [
          {
            "name": "storeId",
            "in": "path",
            "description": "A unique ID generated by ShipStation and assigned to each store.",
            "required": true,
            "x-example": "12345",
            "type": "number"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Get~1Update StoreModel"
            }
          }
        ],
        "produces": [
          "application/json"
        ]
      }
    }
  },
  "definitions": {
    "Get/Update Store": {},
    "Get/Update StoreModel": {
      "type": "object",
      "properties": {
        "storeId": {
          "type": "number"
        },
        "storeName": {
          "type": "string"
        },
        "marketplaceId": {
          "type": "number"
        },
        "marketplaceName": {
          "type": "string"
        },
        "accountName": {
          "type": "null"
        },
        "email": {
          "type": "null"
        },
        "integrationUrl": {
          "type": "string"
        },
        "active": {
          "type": "boolean"
        },
        "companyName": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "publicEmail": {
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "refreshDate": {
          "type": "string"
        },
        "lastRefreshAttempt": {
          "type": "string"
        },
        "createDate": {
          "type": "string"
        },
        "modifyDate": {
          "type": "string"
        },
        "autoRefresh": {
          "type": "boolean"
        },
        "statusMappings": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "orderStatus": {
                "type": "string"
              },
              "statusKey": {
                "type": "string"
              }
            },
            "required": [
              "orderStatus",
              "statusKey"
            ]
          }
        }
      },
      "example": {
        "storeId": 12345,
        "storeName": "WooCommerce Store",
        "marketplaceId": 36,
        "marketplaceName": "WooCommerce",
        "accountName": null,
        "email": null,
        "integrationUrl": "http://shipstation-test.wpengine.com",
        "active": true,
        "companyName": "",
        "phone": "",
        "publicEmail": "",
        "website": "",
        "refreshDate": "2014-12-16T17:47:05.457",
        "lastRefreshAttempt": "2014-12-16T09:47:05.457",
        "createDate": "2014-11-06T15:21:13.223",
        "modifyDate": "2014-11-10T08:02:19.117",
        "autoRefresh": true,
        "statusMappings": [
          {
            "orderStatus": "awaiting_payment",
            "statusKey": "Pending"
          },
          {
            "orderStatus": "awaiting_shipment",
            "statusKey": "Processing"
          },
          {
            "orderStatus": "shipped",
            "statusKey": "Completed"
          },
          {
            "orderStatus": "cancelled",
            "statusKey": "Cancelled"
          },
          {
            "orderStatus": "on_hold",
            "statusKey": "On-hold"
          }
        ]
      }
    }
  },
  "securityDefinitions": {},
  "tags": [
    {
      "name": "Stores"
    }
  ]
}